### ISSUE TITLE
Mention to specify the service with layer id in the doc

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter-scripts#2]
Mention to specify the service with layer id in the [doc](http://solutionsdev.arcgis.com/local-government/help/crowdsource-reporter/get-started/generate-ids/)

Step 6: 'url': The URL to the REST endpoint of the service (ArcGIS Online and Portal) or the path to the feature class that is the source of the service data (ArcGIS Server)

**Comment by allisonmuise** [comment]
updated in both script comments and doc
