### ISSUE TITLE
Define Portal Settings enhancement to get Portal connections in Pro

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter-scripts#28]
What if instead of asking the user to input their Portal URL, you make it a pick list using URLs the user added to Pro. You can use arcpy.ListPortalURLs() to return all the Portal URLs the user currently has added to Pro. You can use GetActivePortalURL() to set the default for the parameter to the active portal. I think this would be a nice enhancement and get around the issue of the user typing in the url incorrectly. I think it is ok to restrict them to Portals defined in Pro because the Feature Layer params in other tools will fail to validate the service if it is secured and you don’t have a valid Portal connection to it.

Similarly for the username you can use arcpy.GetPortalDescription(URL)['user']['username'] to get the username for the portal connection and default that when they select a Portal URL. You need to check if the key ‘user’ exists in the returned dictionary because if they are not signed in this key won’t exist.

**Comment by allisonmuise** [comment]
i like it! Thanks for the suggestion

**Comment by allisonmuise** [comment]
done - please check and close if it's working how you expected @chris-fox

**Comment by chris-fox** [comment]
Looks good, the only feature i might add to the validation is if you select a different portal in the dropdown that you update the username param to the logged in user for that portal.

**Comment by allisonmuise** [comment]
When I try to do this it causes errors when i try to read in values from the config without being signed in to that org which i think will be the more common workflow.
