### ISSUE TITLE
Recommend using %c for strftime of value subsitution

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter-scripts#30]
In the _get_value function dates are being formatted as '%d-%m-%Y %H:%M:%S'. If you use '%c' instead the date/time will be returned in the system locale’s appropriate date and time representation.

                try:
                    val = dt.fromtimestamp(
                        row.attributes[sub]).strftime('%c')
                except OSError:  # timestamp in milliseconds
                    val = dt.fromtimestamp(
                        row.attributes[sub] / 1000).strftime('%c')

**Comment by allisonmuise** [comment]
fixed
