### ISSUE TITLE
Send Email parameter help

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter-scripts#31]
- [x] email spelled wrong in tool metadata tags
- [x] typo in 'Sent Values' in SQL Query description in email settings param
- [x] typo in 'sending' in Sent Value description in email settings param
- [x] I think the information about authenticating through a port is misleading in the smtp_server, username and password params. To send an e-mail through my gmail I need to provide the port and my gmail username and password. I think the fact that username and password are optional params is enough to say they are not required and it is unrelated to providing a port.
- [x] typo in Reply Address param help 'replies sto the'

**Comment by allisonmuise** [comment]
changes made
