### ISSUE TITLE
Replace "sequence type" with "id-name" in the doc

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter-scripts#5]
Step 9 in the http://solutionsdev.arcgis.com/local-government/help/crowdsource-reporter/get-started/generate-ids/

In the doc, replace "sequence type" with "id-name" to match with the column name in the csv.

**Comment by allisonmuise** [comment]
updated all occurrences to 'sequence name' and used 'pattern' to reference the text sequence.
