### ISSUE TITLE
ENH-000114300  Allow apps that use crowd source reporter to moderate comments.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter-scripts#51]
<div><div>
<span><b>Salesforce ID:</b> <a href="https://qamonitor/SFTriage?sfid=ENH-000114300">ENH-000114300</a></span><br/>
<span><b>Salesforce Submitter:</b> Katrina McLean</span><br/>
<span><b>Salesforce Submit Date:</b> 5/29/2018 10:57 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Low</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> User Story: It would be good to be able to moderate the comments so that any inappropriate comments can be removed. It would be best to have this adapted in the moderate reports stand alone script, but alternatively this would be a great option in ArcGIS Online from the solutions deployment tool.<br><br>Steps to Demonstrate:<br>Install the moderate reports toolbox and try to moderate comments in a related table. It will give an error.<br>Deploy Crowd Reporting application. There is no option to moderate incoming comments.</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> (n/a)</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
We will not be enhancing this tool with this feature.
