### ISSUE TITLE
ENH-000116673  Provide the ability to enter multiple email addresses in the Recipient Email Address section when using the Send Emails script found within the ServiceFunctions toolbox.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter-scripts#54]
<div><div>
<span><b>Salesforce ID:</b> <a href="https://qamonitor/SFTriage?sfid=ENH-000116673">ENH-000116673</a></span><br/>
<span><b>Salesforce Submitter:</b> Matthew Metten</span><br/>
<span><b>Salesforce Submit Date:</b> 9/10/2018 2:37 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> User Story: The user and his organization is utilizing this Solution/Send Email tool to send emails to a large number of people (20 to 40). The overall workflow would require the user to redundantly add the same information (Email Template, SQL Query, etc) 20 to 40 times just to include more than recipient. Providing/allowing this functionality would increase the efficiency of the tool and also allow for a more streamlined/modern tool for setting up such a function. <br><br>Steps to Demonstrate: 
<ol><li><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">Download and extract the ServiceFunctions toolbox. </span></span></span></li><li><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">Open the toolbox in ArcGIS Pro 2.x and, if you&#39;ve never used the toolbox before, run the Define Connection Settings tool to establish a connection between the toolbox and the ArcGIS Enterprise portal or ArcGIS Online organization containing the layers which will be used to trigger and generate the emails.</span></span></span></li><li><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">Open the Send Emails tool.</span></span></span></li><li><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">If the tool has not been run previously, start by specifying the connection information for your SMTP server in the General Email Settings section of the tool by providing the following values:</span></span></span></li></ol>

<ul style="margin-left: 80px;"><li><b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">SMTP Server</span></span></span></b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">—URL of the SMTP server used for sending emails (within Esri network: SMTP.esri.com:25)</span></span></span></li><li><b><span><span style="font-size: 12.0pt;">If outside the network:</span></span></b></li><li><b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">SMTP Username</span></span></span></b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">—The username required to authenticate to the SMTP server. This is not required if authenticating through a port.</span></span></span></li><li><b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">SMTP Password</span></span></span></b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">—The password required to authenticate to the SMTP server. This is not required if authenticating through a port.</span></span></span></li><li><b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">From Address</span></span></span></b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">—The address from which the emails should be sent.</span></span></span></li><li><b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">Reply Address</span></span></span></b><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">—The address that should be used for any replies to the email message.</span></span></span></li></ul>

<ol><li><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">Browse to the path of an HTML template for the body of the email (found in the servicesupport download folder).</span></span></span></li><li><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">Provide a valid SQL Query (1=1)</span></span></span></li><li><span><span style="font-family: lucida grande,serif;"><span style="font-size: 12.0pt;">Provide the email address of the recipient and note that nowhere in the doc or the tool does it explain if you can or cannot add multiple recipients. Additionally, adding any delimiter and an additional email address does not provide the ability to send the email to multiple recipients.</span></span></span></li><li><span><span style="font-size: 12.0pt;">Provide a subject and a field to update and select Run.</span></span></li><li><span><span style="font-size: 12.0pt;">Navigate to the send_email Python script and run with ArcGIS Pro IDLE.</span></span></li><li><span><span style="font-size: 12.0pt;">Overall outcome will be one recipient even if multiple addresses are added. In the received email it shows the other addresses but these are never actually sent properly. </span></span></li></ol></span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 2.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by UnderJollyRoger** [comment]
Hi Allison,

I'm attempting to send multiple emails, but my emails are four separate Email Settings because each one uses a query to grab a certain field and then sends to its corresponding recipient. The tool states that emails will be sent in the order listed. I'm finding that only the Recipient Email Address in the top one is being used, while the other Recipient Email Addresses are ignored. Have you seen this behavior?

![image](https://user-images.githubusercontent.com/32503258/75565897-6e9f4980-5a14-11ea-8d24-dd215fcbd415.png)

**Comment by allisonmuise** [comment]
@UnderJollyRoger I can't see your full SQL queries, but from what I can see, I would only expect the first one to work. The reason for this is if an email meets the first SQL query, the email will be sent and the send_email field for tht feature will be updated to have the value 'sent'. This would exclude that record from any of the subsequent queries which, from what I can see, require that field to be either NULL or "".

**Comment by UnderJollyRoger** [comment]
Thanks for the response. Here are the SQL Queries ordered as above:

send_email IS NULL Or send_email = '""' And field_2 = 'parcel_or_pin_question?'
send_email IS NULL Or send_email = '""' And field_2 = 'street_or_address_question?'
send_email IS NULL Or send_email = '""' And field_2 = 'tax_related_question?'
send_email IS NULL Or send_email = '""' And field_2 = 'zoning_or_flood_zone_question?'
send_email = '""' Or send_email IS NULL And field_2 = 'other'

I have a feature layer that's populated from Survey123. To test the Send Emails tool, I submitted 5 surveys, one for each category. I was assuming the emails would be sent by meeting the field_2 argument, and when it did the send_email field would be populated. Then, I thought it would move on to the next email. But, in this case the first recipient got all five emails. But, at least each email had one of the five category's in place of a keyword.

My purpose through the survey is to have the question sent in an email to its corresponding county department.

**Comment by allisonmuise** [comment]
I see what you are trying to do now. It does still sound like there is a logical flaw in the queries. Try using each of those queries to select records from the REST endpoint of the service. To do what you are describing, only one feature should be returned by each query.

**Comment by UnderJollyRoger** [comment]
@allisonmuise It seems you were right about the flawed logic. I've removed `Or send_email = "''"`. Now the queries seem to be triggering the correct emails to the correct recipients. 

I was wondering if I could ask you something else. I have the email template set up so it looks for a key word and swaps it for a field in the table. This table belongs to a feature created through Survey123. The problem is the table shows one thing and the triggered email shows another. I can see where `street_or_address_question?` is coming from in the Survey123 XLSForm, but I want `label` to show up in the email not `name`.

Table:
![image](https://user-images.githubusercontent.com/32503258/75822916-66257680-5d66-11ea-9df7-ba1d1efadecd.png)

Email:
![ex](https://user-images.githubusercontent.com/32503258/75823131-ce745800-5d66-11ea-8f31-b24839df0471.png)

Survey123 XLSForm:
![expor](https://user-images.githubusercontent.com/32503258/75823626-b6510880-5d67-11ea-88af-709938f19f69.png)

**Comment by allisonmuise** [comment]
This is a known limitation with this tool. it displays the field value not the alias associated with that value.

**Comment by UnderJollyRoger** [comment]
@allisonmuise OK, thank you for the response. Are there any known work-arounds to get the field value to display?

**Comment by allisonmuise** [comment]
#56
