### ISSUE TITLE
Connect2Cityworks.pyt KeyError operationalLayers

### ISSUE THREAD

**Issue by akung21** [Esri/crowdsource-reporter-scripts#64]
When I try to run the Connect2Cityworks tool in ArcGIS Pro, I get a KeyError on 'operationalLayers'. It looks like this line is causing the issue:
`for layer in webmap['operationalLayers']:`

Changing the line to the following appears to resolve the issue:
`for layer in webmap.definition['operationalLayers']:`

**Comment by akung21** [comment]
Turns out I was accessing the Connect2Cityworks.pyt file from the 'update-workforce' branch, which has the old line:
https://github.com/Esri/crowdsource-reporter-scripts/blob/update-workforce/CityworksConnection/Connect2Cityworks.pyt

For future reference, which branch should I be checking for the latest version of this script?

Thank you for your prompt response!

**Comment by aparker-cityworks** [comment]
The develop branch will have the latest.
